### ISSUE TITLE
Add `execute` resource

### ISSUE THREAD

**Issue by puetzp** [puetzp/pullconf#1]
As the title says, an `execute` resource should be added that runs arbitrary commands on the client, ideally as a result of another action, such as a changed `file`.

Every other existing resource should be extended with a `trigger` meta-parameter on the same level as `requires`. The `trigger` parameter could be an array of references to `execute` resources. When the resource exits with `changed`, `created` or `deleted`, all referenced `execute` resources are triggered to run in order.

When the same `execute` resource is referenced multiple times, running the command will be delayed until all referencing resources have run and at least one exits with `changed`, `created` or `deleted`.

In a first iteration, the `execute` resource could look like this:

```yaml
resources:
  - type: execute
    parameters:
      command:
        - /usr/local/sbin/my-script
        - some-arg
        - another-arg
        - etc.
```

The resource will be harcoded with a hidden `passive` parameter that is set to `true` which will cause the resource to run only when triggered by other resources. This satisfies probably the most common use case, that is reloading a service or doing something similar when a configuration file changes.

As for validation resources can only reference existing `execute` resources.

Example:

```yaml
resources:
  - type: file
    parameters:
      path: /etc/ssh/sshd_config
      source: /${pullconf::hostname}/etc/ssh/sshd_config
    trigger:
      - type: execute
        name: reload-sshd

  - type: execute
    parameters:
      name: reload-sshd
      command:
        - systemctl
        - reload
        - sshd.service
```

On a second iteration the `execute` resource should be able to run on its own according to some condition. In this case `passive` can be set to `false` to enable conditional behavior.

A use case for running a command based on a condition is changing a single line in a configuration file that is supplied by some package, e.g. to ensure `/etc/fstab` mentions a specific mount point to be mounted at boot.
