### ISSUE TITLE
Make variables subscriptable

### ISSUE THREAD

**Issue by puetzp** [puetzp/pullconf#6]
Since StrictYAML parses all literals as strings, variables fit into configuration files seamlessly without having to quote them:

```yaml
number: 400
line: some string
variable: ${pullconf::some-variable}
```

Right now variables need to resolve to the same type that is expected from the parameter where the variable is found or resolve to a string if substring substitution is used inside another string parameter:

```yaml
variables:
  ip: 192.168.0.200
  mode: 0600

resources:
  - type: host
    parameters:
      ip_address: ${pullconf::ip}
      hostname: ${pullconf::hostname}
      aliases:
        - me
        - myself
        - I
  - type: file
    parameters:
      path: /etc/ssh/sshd_config
      content: |
        ...
        Listen ${pullconf::ip}
        ...
```

It would be useful if variables were subscriptable in a way so values inside hash and array variables can be accessed:

```yaml
variables:
  sshd:
    port: 22
    ip: 192.168.0.200

  - type: file
    parameters:
      path: /etc/ssh/sshd_config
      mode: ${pullconf::mode}
      content: |
        ...
        Listen ${pullconf::sshd.ip}
        Port ${pullconf::sshd.port}
        ...
```

The syntax for accessing values inside hashes and arrays could be:

- dots for accessing keys inside hashes
- numbers inside square brackets to access array elements

Making variables subscriptable allows users to organize their variables better.

Possible issues: Variables should still be able to contain other variables. Resolving variables thus becomes a little more complex.
